// Отдельная БД для хранения связей тэгов и локаций,
// в каждой шарде информация будет дублироваться.
//  Таким образом, список тэгов и локаций будет единым на все шарды

// Replication: master-master sync
// RF = 2
// Sharding: NO, savind in current db, choosen by request

Table tag {
  id uuid [primary key]
  name varchar (25)
  count int
}

Table place {
  id uuid
  location decimal
  like_count count
  dislike_count count 
}

Table tag_place {
  place_id uuid
  tag_id uuid
}

Ref: "tag"."id" < "tag_place"."tag_id"

Ref: "place"."id" < "tag_place"."place_id"